### ISSUE TITLE
Comparison to other async stream crates

### ISSUE THREAD

**Issue by malthe** [taiki-e/futures-async-stream#67]
How does this compare to https://crates.io/crates/async-stream.

**Comment by taiki-e** [comment]
(I disabled GitHub discussions, so copying the answer from GitHub discussions for the record.)
- async-stream supports stable rust. futures-async-stream only supports nightly rust.
- futures-async-stream supports `no_std` environment. async-stream requires `std`.
- futures-async-stream is a bit more efficient because it uses a generator directly and doesn't depend on TLS.
